name: Reusable workflow test too

on:
  workflow_call:
    inputs:
      anotherInput:
        required: true
        type: string

jobs:
  anotherJob:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.anotherInput }}!
